import bands from "../strata-data.json";

// The layered night landscape behind the home page. The band shapes are
// pre-generated by scripts/generate-strata.mjs; positioning is pure CSS
// (see root.css) — each band's bottom chains to the next band's top, so
// the layers track the document height with no measuring.
export function Strata() {
  return (
    <div id="strata" aria-hidden="true">
      {bands.map((band) => (
        <div
          key={band.top}
          className="band"
          style={{ top: band.top, bottom: band.bottom }}
        >
          <svg
            className="back"
            viewBox="0 0 1440 120"
            preserveAspectRatio="none"
          >
            <path d={band.back} fill={band.fill} fillOpacity="0.45" />
          </svg>
          <svg viewBox="0 0 1440 120" preserveAspectRatio="none">
            <path d={band.front} fill={band.fill} />
          </svg>
          <div className="body" style={{ background: band.bodyBackground }} />
        </div>
      ))}
    </div>
  );
}
